export const sections = [
  { id: 'flowers', title: 'Flowers', hint: 'The bouquet for no particular occasion.', preview: 'flowers', heading: 'Just because you exist', caption: 'No occasion. Just you.', artText: 'NO OCCASION NEEDED.', message: 'No big occasion. I just like you, and I want you to know it.' },
  { id: 'cafe', title: 'Photo 1', hint: 'The first portrait card. Send your own photo in Telegram.', heading: 'You make it hard to play it cool', caption: 'Casually making my whole day.', message: 'I keep coming back to this photo and smiling at my phone like that isn’t obvious.' },
  { id: 'chat', title: 'Phone chat', hint: 'Two messages that appear one at a time.', preview: 'chat', heading: 'My screen time has a name', caption: 'Your text. My whole mood.', artText: 'you busy?\nfor you? never.', message: 'Your name lights up my phone and suddenly I’m smiling at a screen.' },
  { id: 'tickets', title: 'The date ticket', hint: 'A paper ticket for the two of you.', preview: 'tickets', heading: 'Me + you + literally anywhere', caption: 'First date energy.', artText: 'A PLAN FOR US\nAdmit two.\nAnywhere with you.\nYES TO US\nI’d pick you. Every time.', message: 'I want to take you on an actual date. The plan can be simple. Having you there is the good part.' },
  { id: 'note', title: 'Sticky note', hint: 'The yellow note with typing and an underline.', preview: 'note', heading: 'A thought I keep having', caption: 'No plans to evict you.', artText: 'you live in\nmy head.\nrent free.\nand the decor’s pretty great.', message: 'You keep showing up in my thoughts at the most random times. I’m not even fighting it anymore.' },
  { id: 'night', title: 'Late night', hint: 'The moon and twinkling stars.', preview: 'night', heading: '“One last text” was a lie', caption: 'Worth losing sleep over.', artText: 'one more text.\nand suddenly it’s 2 am.', message: 'One more story, one more goodnight, one more excuse to talk to you.' },
  { id: 'wink', title: 'Photo 2', hint: 'The second photo card. Send your own photo in Telegram.', heading: 'I’d take the long way with you', caption: 'A walk with you counts as a plan.', message: 'I’d take the long way home if it meant a little more time with you.' },
  { id: 'drink', title: 'Something sweet', hint: 'The pink drink with moving ice.', preview: 'drink', heading: 'A little too sweet on you', caption: 'I’d call this a date.', artText: 'sweet on you.', message: 'Let me buy you something sweet and call it what it is: a date.' },
  { id: 'playlist', title: 'The playlist', hint: 'The spinning record. Music is selected by your song title.', preview: 'playlist', heading: 'Your unofficial soundtrack', caption: 'Best Part, on repeat.', artText: 'songs that sound like you.\non repeat. obviously.', message: 'Every other song reminds me of you now. Pretty sure that’s a good sign.' },
];
